### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by rogerleite** [mrmrs/mnml#1]
Before anything, thank you for publishing things like this, awesome work!
What do you think about these sugestions:
* Tag some kind of "stable" version.
* Support themes.

The last sugestion would be great for people like me, that is looking for clean bootstrap.

Thanks.

**Comment by mrmrs** [comment]
@rogerleite I don't want any themes in this project - but eventually will get around to building some light weight themes in a different project. Thanks for the suggestion!
