### ISSUE TITLE
What about JS ?

### ISSUE THREAD

**Issue by chrisvidal** [mrmrs/mnml#14]
Hi,
great work, love it.
I feel like JS should be handled as well with gulp ?
Thanks

**Comment by mrmrs** [comment]
I don't know much about good js build systems and feel that would be a separate project. I did include js build stuff in an earlier version of mnml but it just never felt right. This is more for simple sites that don't require js at all. I have another project that is very similar to mnml but also include asset optimization and js build flow called trim if you want to check it out (very outdated though)
