### ISSUE TITLE
localhost:3001 is just a BrowserSync page

### ISSUE THREAD

**Issue by bclinkinbeard** [mrmrs/mnml#17]
Running npm start then opening localhost:3001 just shows a BS admin page. Am I missing something?

**Comment by bclinkinbeard** [comment]
Looks like `npm start` should be `browser-sync start --server --files './*'`. The `--server` is needed to see your output.

**Comment by mrmrs** [comment]
@bclinkinbeard Thanks for the tip! Somehow missed this.

**Comment by mrmrs** [comment]
Closed as this is fixed.
