### ISSUE TITLE
With latest gulp update, gulp-watch plugin breaks due to function

### ISSUE THREAD

**Issue by wigggins** [mrmrs/mnml#9]
Hi Adam -

It appears that a gulp update may have broken the gulp-watch plugin using your current configuration in the gulpfile. I'm receiving the following error:
```
[13:50:33] Using gulpfile /Users/_____/Documents/www/mnml/gulpfile.js
[13:50:33] Starting 'pre-process'...
[13:50:33] 'pre-process' errored after 4.81 ms
[13:50:33] Error in plugin 'gulp-watch'
Message:
    glob should be String or Array, not function
```
Looked into it a bit, and it seems to be referencing line 53 of gulpfile.js.

I'm running gulp v3.8.11

**Comment by mrmrs** [comment]
Yep! This was indeed broken. Thanks for calling my attention to this. Should be fixed with the latest version. Let me know if it still doesn't work for you though.
